version: '3.8'
services:  
  backend:    
    build: ./backend   
    container_name: server_bd   
    ports:      
      - '3001:3001'    
    depends_on:
      - mongo
    networks:
      - mongo-networks
  mongo:
    image: mongo
    restart: always
    networks:
      - mongo-networks
  frontend:    
    build: ./frontend  
    container_name: client_react 
    ports:      
      - '3000:3000'    
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mongo-networks
networks:
  mongo-networks: